# Code generated by scripts/src/generate-sdk-python.ts. DO NOT EDIT.
"""The route registry: what every operation is called and where it lives.

The client dispatches on this, and so can anything built on top of it. It is the
same data the TypeScript SDK exposes from ``pgbeam/operations``, in the same
shape, so tooling that walks one can walk the other.
"""

from __future__ import annotations

from typing import NamedTuple

__all__ = ["OPERATIONS_BY_PATH", "OPERATIONS_BY_TAG", "OperationMeta"]


class OperationMeta(NamedTuple):
    """One operation's HTTP method and path template."""

    method: str
    path: str


OPERATIONS_BY_TAG: dict[str, dict[str, OperationMeta]] = {
    "projects": {
        "list_cache_rules": OperationMeta(
            "GET", "/v1/projects/{project_id}/databases/{database_id}/cache-rules"
        ),
        "update_cache_rule": OperationMeta(
            "PUT", "/v1/projects/{project_id}/databases/{database_id}/cache-rules/{query_hash}"
        ),
        "list_custom_domains": OperationMeta("GET", "/v1/projects/{project_id}/domains"),
        "create_custom_domain": OperationMeta("POST", "/v1/projects/{project_id}/domains"),
        "delete_custom_domain": OperationMeta(
            "DELETE", "/v1/projects/{project_id}/domains/{domain_id}"
        ),
        "verify_custom_domain": OperationMeta(
            "POST", "/v1/projects/{project_id}/domains/{domain_id}/verify"
        ),
        "list_projects": OperationMeta("GET", "/v1/projects"),
        "create_project": OperationMeta("POST", "/v1/projects"),
        "get_project": OperationMeta("GET", "/v1/projects/{project_id}"),
        "update_project": OperationMeta("PATCH", "/v1/projects/{project_id}"),
        "delete_project": OperationMeta("DELETE", "/v1/projects/{project_id}"),
        "get_project_metrics": OperationMeta("GET", "/v1/projects/{project_id}/metrics"),
        "list_replicas": OperationMeta("GET", "/v1/databases/{database_id}/replicas"),
        "create_replica": OperationMeta("POST", "/v1/databases/{database_id}/replicas"),
        "delete_replica": OperationMeta(
            "DELETE", "/v1/databases/{database_id}/replicas/{replica_id}"
        ),
    },
    "databases": {
        "list_databases": OperationMeta("GET", "/v1/projects/{project_id}/databases"),
        "create_database": OperationMeta("POST", "/v1/projects/{project_id}/databases"),
        "get_database": OperationMeta("GET", "/v1/projects/{project_id}/databases/{database_id}"),
        "update_database": OperationMeta(
            "PATCH", "/v1/projects/{project_id}/databases/{database_id}"
        ),
        "delete_database": OperationMeta(
            "DELETE", "/v1/projects/{project_id}/databases/{database_id}"
        ),
        "test_database_connection": OperationMeta(
            "POST", "/v1/projects/{project_id}/databases/{database_id}/test-connection"
        ),
        "scan_database_for_pii": OperationMeta(
            "POST", "/v1/projects/{project_id}/databases/{database_id}/scan-pii"
        ),
        "get_schema_catalog": OperationMeta(
            "GET", "/v1/projects/{project_id}/databases/{database_id}/schema-catalog"
        ),
    },
    "policies": {
        "recommend_agent_policy": OperationMeta(
            "POST", "/v1/projects/{project_id}/agents/{agent_id}/policy-recommendation"
        ),
        "list_policy_profiles": OperationMeta("GET", "/v1/projects/{project_id}/policies"),
        "create_policy_profile": OperationMeta("POST", "/v1/projects/{project_id}/policies"),
        "get_policy_profile": OperationMeta(
            "GET", "/v1/projects/{project_id}/policies/{policy_id}"
        ),
        "update_policy_profile": OperationMeta(
            "PUT", "/v1/projects/{project_id}/policies/{policy_id}"
        ),
        "delete_policy_profile": OperationMeta(
            "DELETE", "/v1/projects/{project_id}/policies/{policy_id}"
        ),
        "dry_eval_policy": OperationMeta("POST", "/v1/projects/{project_id}/policy-evaluations"),
        "replay_policy": OperationMeta("POST", "/v1/projects/{project_id}/policy-replays"),
    },
    "agents": {
        "list_agent_credentials": OperationMeta("GET", "/v1/projects/{project_id}/agents"),
        "create_agent_credential": OperationMeta("POST", "/v1/projects/{project_id}/agents"),
        "get_agent_credential": OperationMeta("GET", "/v1/projects/{project_id}/agents/{agent_id}"),
        "update_agent_credential_status": OperationMeta(
            "PATCH", "/v1/projects/{project_id}/agents/{agent_id}"
        ),
        "revoke_agent_credential": OperationMeta(
            "DELETE", "/v1/projects/{project_id}/agents/{agent_id}"
        ),
        "rotate_agent_credential": OperationMeta(
            "POST", "/v1/projects/{project_id}/agents/{agent_id}/rotate"
        ),
        "list_audit_logs": OperationMeta("GET", "/v1/projects/{project_id}/audit-logs"),
        "export_audit_logs": OperationMeta("GET", "/v1/projects/{project_id}/audit-logs/export"),
        "get_audit_session_summary": OperationMeta(
            "GET", "/v1/projects/{project_id}/audit-logs/sessions/{session_id}"
        ),
        "verify_audit_chain": OperationMeta("GET", "/v1/projects/{project_id}/audit-logs/verify"),
        "get_agent_usage_breakdown": OperationMeta("GET", "/v1/projects/{project_id}/usage/agents"),
    },
    "approvals": {
        "list_approval_requests": OperationMeta("GET", "/v1/projects/{project_id}/approvals"),
        "approve_approval_request": OperationMeta(
            "POST", "/v1/projects/{project_id}/approvals/{approval_id}/approve"
        ),
        "reject_approval_request": OperationMeta(
            "POST", "/v1/projects/{project_id}/approvals/{approval_id}/reject"
        ),
    },
    "webhooks": {
        "list_webhook_endpoints": OperationMeta("GET", "/v1/projects/{project_id}/webhooks"),
        "create_webhook_endpoint": OperationMeta("POST", "/v1/projects/{project_id}/webhooks"),
        "get_webhook_endpoint": OperationMeta(
            "GET", "/v1/projects/{project_id}/webhooks/{webhook_id}"
        ),
        "update_webhook_endpoint": OperationMeta(
            "PUT", "/v1/projects/{project_id}/webhooks/{webhook_id}"
        ),
        "delete_webhook_endpoint": OperationMeta(
            "DELETE", "/v1/projects/{project_id}/webhooks/{webhook_id}"
        ),
        "test_webhook_endpoint": OperationMeta(
            "POST", "/v1/projects/{project_id}/webhooks/{webhook_id}/test"
        ),
    },
    "honeytokens": {
        "list_honeytokens": OperationMeta("GET", "/v1/projects/{project_id}/honeytokens"),
        "create_honeytoken": OperationMeta("POST", "/v1/projects/{project_id}/honeytokens"),
        "get_honeytoken": OperationMeta(
            "GET", "/v1/projects/{project_id}/honeytokens/{honeytoken_id}"
        ),
        "update_honeytoken": OperationMeta(
            "PUT", "/v1/projects/{project_id}/honeytokens/{honeytoken_id}"
        ),
        "delete_honeytoken": OperationMeta(
            "DELETE", "/v1/projects/{project_id}/honeytokens/{honeytoken_id}"
        ),
    },
    "schema_annotations": {
        "list_schema_annotations": OperationMeta(
            "GET", "/v1/projects/{project_id}/schema-annotations"
        ),
        "put_schema_annotation": OperationMeta(
            "PUT", "/v1/projects/{project_id}/schema-annotations"
        ),
        "delete_schema_annotation": OperationMeta(
            "DELETE", "/v1/projects/{project_id}/schema-annotations"
        ),
    },
    "anomalies": {
        "list_anomaly_alerts": OperationMeta("GET", "/v1/projects/{project_id}/anomalies"),
        "update_anomaly_alert": OperationMeta(
            "PATCH", "/v1/projects/{project_id}/anomalies/{anomaly_id}"
        ),
    },
    "branches": {
        "list_database_branches": OperationMeta("GET", "/v1/projects/{project_id}/branches"),
        "discard_database_branch": OperationMeta(
            "DELETE", "/v1/projects/{project_id}/branches/{branch_id}"
        ),
    },
    "migrations": {
        "lint_migration": OperationMeta("POST", "/v1/projects/{project_id}/migrations:lint"),
    },
    "analytics": {
        "list_plans": OperationMeta("GET", "/v1/plans"),
        "get_organization_plan": OperationMeta("GET", "/v1/organizations/{org_id}/plan"),
        "get_vercel_installation": OperationMeta(
            "GET", "/v1/organizations/{org_id}/vercel-installation"
        ),
        "update_spend_limit": OperationMeta("PUT", "/v1/organizations/{org_id}/spend-limit"),
        "submit_cancellation_feedback": OperationMeta(
            "POST", "/v1/organizations/{org_id}/cancellation-feedback"
        ),
        "get_project_insights": OperationMeta("GET", "/v1/projects/{project_id}/insights"),
        "get_organization_usage": OperationMeta("GET", "/v1/organizations/{org_id}/usage"),
        "get_project_usage": OperationMeta("GET", "/v1/projects/{project_id}/usage"),
    },
    "platform": {
        "get_health": OperationMeta("GET", "/v1/health"),
        "list_regions": OperationMeta("GET", "/v1/regions"),
        "list_self_host_enrollments": OperationMeta(
            "GET", "/v1/organizations/{org_id}/self-host-enrollments"
        ),
        "create_self_host_enrollment": OperationMeta(
            "POST", "/v1/organizations/{org_id}/self-host-enrollments"
        ),
        "revoke_self_host_enrollment": OperationMeta(
            "DELETE", "/v1/organizations/{org_id}/self-host-enrollments/{enrollment_id}"
        ),
        "rotate_self_host_enrollment": OperationMeta(
            "POST", "/v1/organizations/{org_id}/self-host-enrollments/{enrollment_id}/rotate"
        ),
        "scan_text": OperationMeta("POST", "/v1/scan/text"),
    },
    "account": {
        "export_account_data": OperationMeta("GET", "/v1/account/export"),
        "list_org_members": OperationMeta("GET", "/v1/organizations/{org_id}/members"),
        "update_org_member_role": OperationMeta(
            "PATCH", "/v1/organizations/{org_id}/members/{member_id}"
        ),
        "remove_org_member": OperationMeta(
            "DELETE", "/v1/organizations/{org_id}/members/{member_id}"
        ),
        "list_org_invitations": OperationMeta("GET", "/v1/organizations/{org_id}/invitations"),
        "create_org_invitation": OperationMeta("POST", "/v1/organizations/{org_id}/invitations"),
        "revoke_org_invitation": OperationMeta(
            "DELETE", "/v1/organizations/{org_id}/invitations/{invitation_id}"
        ),
        "get_onboarding_progress": OperationMeta("GET", "/v1/organizations/{org_id}/onboarding"),
        "update_onboarding_progress": OperationMeta(
            "PATCH", "/v1/organizations/{org_id}/onboarding"
        ),
        "list_organizations": OperationMeta("GET", "/v1/organizations"),
    },
    "support": {
        "list_support_cases": OperationMeta("GET", "/v1/organizations/{org_id}/support/cases"),
        "create_support_case": OperationMeta("POST", "/v1/organizations/{org_id}/support/cases"),
        "get_support_case": OperationMeta(
            "GET", "/v1/organizations/{org_id}/support/cases/{case_id}"
        ),
        "update_support_case": OperationMeta(
            "PATCH", "/v1/organizations/{org_id}/support/cases/{case_id}"
        ),
        "create_support_message": OperationMeta(
            "POST", "/v1/organizations/{org_id}/support/cases/{case_id}/messages"
        ),
    },
    "batch": {
        "execute_batch": OperationMeta("POST", "/v1/projects/{project_id}/batch"),
    },
    "demo": {
        "get_demo": OperationMeta("GET", "/v1/demo"),
        "create_demo_credential": OperationMeta("POST", "/v1/demo/credentials"),
        "release_demo_credential": OperationMeta(
            "POST", "/v1/demo/credentials/{session_id}/release"
        ),
    },
    "internal": {
        "handle_slack_support_event": OperationMeta("POST", "/v1/internal/support/slack-event"),
    },
    "payments": {
        "list_payment_resources": OperationMeta("GET", "/v1/payments/resources"),
        "create_budget_topup": OperationMeta("POST", "/v1/payments/budget-topups"),
    },
}

OPERATIONS_BY_PATH: dict[str, OperationMeta] = {
    "GET /v1/account/export": OperationMeta("GET", "/v1/account/export"),
    "GET /v1/projects/{project_id}/agents": OperationMeta(
        "GET", "/v1/projects/{project_id}/agents"
    ),
    "POST /v1/projects/{project_id}/agents": OperationMeta(
        "POST", "/v1/projects/{project_id}/agents"
    ),
    "GET /v1/projects/{project_id}/agents/{agent_id}": OperationMeta(
        "GET", "/v1/projects/{project_id}/agents/{agent_id}"
    ),
    "PATCH /v1/projects/{project_id}/agents/{agent_id}": OperationMeta(
        "PATCH", "/v1/projects/{project_id}/agents/{agent_id}"
    ),
    "DELETE /v1/projects/{project_id}/agents/{agent_id}": OperationMeta(
        "DELETE", "/v1/projects/{project_id}/agents/{agent_id}"
    ),
    "POST /v1/projects/{project_id}/agents/{agent_id}/rotate": OperationMeta(
        "POST", "/v1/projects/{project_id}/agents/{agent_id}/rotate"
    ),
    "POST /v1/projects/{project_id}/agents/{agent_id}/policy-recommendation": OperationMeta(
        "POST", "/v1/projects/{project_id}/agents/{agent_id}/policy-recommendation"
    ),
    "GET /v1/projects/{project_id}/anomalies": OperationMeta(
        "GET", "/v1/projects/{project_id}/anomalies"
    ),
    "PATCH /v1/projects/{project_id}/anomalies/{anomaly_id}": OperationMeta(
        "PATCH", "/v1/projects/{project_id}/anomalies/{anomaly_id}"
    ),
    "GET /v1/projects/{project_id}/approvals": OperationMeta(
        "GET", "/v1/projects/{project_id}/approvals"
    ),
    "POST /v1/projects/{project_id}/approvals/{approval_id}/approve": OperationMeta(
        "POST", "/v1/projects/{project_id}/approvals/{approval_id}/approve"
    ),
    "POST /v1/projects/{project_id}/approvals/{approval_id}/reject": OperationMeta(
        "POST", "/v1/projects/{project_id}/approvals/{approval_id}/reject"
    ),
    "GET /v1/projects/{project_id}/audit-logs": OperationMeta(
        "GET", "/v1/projects/{project_id}/audit-logs"
    ),
    "GET /v1/projects/{project_id}/audit-logs/export": OperationMeta(
        "GET", "/v1/projects/{project_id}/audit-logs/export"
    ),
    "GET /v1/projects/{project_id}/audit-logs/sessions/{session_id}": OperationMeta(
        "GET", "/v1/projects/{project_id}/audit-logs/sessions/{session_id}"
    ),
    "GET /v1/projects/{project_id}/audit-logs/verify": OperationMeta(
        "GET", "/v1/projects/{project_id}/audit-logs/verify"
    ),
    "POST /v1/projects/{project_id}/batch": OperationMeta(
        "POST", "/v1/projects/{project_id}/batch"
    ),
    "GET /v1/plans": OperationMeta("GET", "/v1/plans"),
    "GET /v1/organizations/{org_id}/plan": OperationMeta("GET", "/v1/organizations/{org_id}/plan"),
    "GET /v1/organizations/{org_id}/vercel-installation": OperationMeta(
        "GET", "/v1/organizations/{org_id}/vercel-installation"
    ),
    "PUT /v1/organizations/{org_id}/spend-limit": OperationMeta(
        "PUT", "/v1/organizations/{org_id}/spend-limit"
    ),
    "POST /v1/organizations/{org_id}/cancellation-feedback": OperationMeta(
        "POST", "/v1/organizations/{org_id}/cancellation-feedback"
    ),
    "GET /v1/projects/{project_id}/branches": OperationMeta(
        "GET", "/v1/projects/{project_id}/branches"
    ),
    "DELETE /v1/projects/{project_id}/branches/{branch_id}": OperationMeta(
        "DELETE", "/v1/projects/{project_id}/branches/{branch_id}"
    ),
    "GET /v1/projects/{project_id}/databases/{database_id}/cache-rules": OperationMeta(
        "GET", "/v1/projects/{project_id}/databases/{database_id}/cache-rules"
    ),
    "PUT /v1/projects/{project_id}/databases/{database_id}/cache-rules/{query_hash}": OperationMeta(
        "PUT", "/v1/projects/{project_id}/databases/{database_id}/cache-rules/{query_hash}"
    ),
    "GET /v1/projects/{project_id}/databases": OperationMeta(
        "GET", "/v1/projects/{project_id}/databases"
    ),
    "POST /v1/projects/{project_id}/databases": OperationMeta(
        "POST", "/v1/projects/{project_id}/databases"
    ),
    "GET /v1/projects/{project_id}/databases/{database_id}": OperationMeta(
        "GET", "/v1/projects/{project_id}/databases/{database_id}"
    ),
    "PATCH /v1/projects/{project_id}/databases/{database_id}": OperationMeta(
        "PATCH", "/v1/projects/{project_id}/databases/{database_id}"
    ),
    "DELETE /v1/projects/{project_id}/databases/{database_id}": OperationMeta(
        "DELETE", "/v1/projects/{project_id}/databases/{database_id}"
    ),
    "POST /v1/projects/{project_id}/databases/{database_id}/test-connection": OperationMeta(
        "POST", "/v1/projects/{project_id}/databases/{database_id}/test-connection"
    ),
    "POST /v1/projects/{project_id}/databases/{database_id}/scan-pii": OperationMeta(
        "POST", "/v1/projects/{project_id}/databases/{database_id}/scan-pii"
    ),
    "GET /v1/projects/{project_id}/databases/{database_id}/schema-catalog": OperationMeta(
        "GET", "/v1/projects/{project_id}/databases/{database_id}/schema-catalog"
    ),
    "GET /v1/demo": OperationMeta("GET", "/v1/demo"),
    "POST /v1/demo/credentials": OperationMeta("POST", "/v1/demo/credentials"),
    "POST /v1/demo/credentials/{session_id}/release": OperationMeta(
        "POST", "/v1/demo/credentials/{session_id}/release"
    ),
    "GET /v1/projects/{project_id}/domains": OperationMeta(
        "GET", "/v1/projects/{project_id}/domains"
    ),
    "POST /v1/projects/{project_id}/domains": OperationMeta(
        "POST", "/v1/projects/{project_id}/domains"
    ),
    "DELETE /v1/projects/{project_id}/domains/{domain_id}": OperationMeta(
        "DELETE", "/v1/projects/{project_id}/domains/{domain_id}"
    ),
    "POST /v1/projects/{project_id}/domains/{domain_id}/verify": OperationMeta(
        "POST", "/v1/projects/{project_id}/domains/{domain_id}/verify"
    ),
    "GET /v1/health": OperationMeta("GET", "/v1/health"),
    "GET /v1/projects/{project_id}/honeytokens": OperationMeta(
        "GET", "/v1/projects/{project_id}/honeytokens"
    ),
    "POST /v1/projects/{project_id}/honeytokens": OperationMeta(
        "POST", "/v1/projects/{project_id}/honeytokens"
    ),
    "GET /v1/projects/{project_id}/honeytokens/{honeytoken_id}": OperationMeta(
        "GET", "/v1/projects/{project_id}/honeytokens/{honeytoken_id}"
    ),
    "PUT /v1/projects/{project_id}/honeytokens/{honeytoken_id}": OperationMeta(
        "PUT", "/v1/projects/{project_id}/honeytokens/{honeytoken_id}"
    ),
    "DELETE /v1/projects/{project_id}/honeytokens/{honeytoken_id}": OperationMeta(
        "DELETE", "/v1/projects/{project_id}/honeytokens/{honeytoken_id}"
    ),
    "GET /v1/projects/{project_id}/insights": OperationMeta(
        "GET", "/v1/projects/{project_id}/insights"
    ),
    "GET /v1/organizations/{org_id}/members": OperationMeta(
        "GET", "/v1/organizations/{org_id}/members"
    ),
    "PATCH /v1/organizations/{org_id}/members/{member_id}": OperationMeta(
        "PATCH", "/v1/organizations/{org_id}/members/{member_id}"
    ),
    "DELETE /v1/organizations/{org_id}/members/{member_id}": OperationMeta(
        "DELETE", "/v1/organizations/{org_id}/members/{member_id}"
    ),
    "GET /v1/organizations/{org_id}/invitations": OperationMeta(
        "GET", "/v1/organizations/{org_id}/invitations"
    ),
    "POST /v1/organizations/{org_id}/invitations": OperationMeta(
        "POST", "/v1/organizations/{org_id}/invitations"
    ),
    "DELETE /v1/organizations/{org_id}/invitations/{invitation_id}": OperationMeta(
        "DELETE", "/v1/organizations/{org_id}/invitations/{invitation_id}"
    ),
    "POST /v1/projects/{project_id}/migrations:lint": OperationMeta(
        "POST", "/v1/projects/{project_id}/migrations:lint"
    ),
    "GET /v1/organizations/{org_id}/onboarding": OperationMeta(
        "GET", "/v1/organizations/{org_id}/onboarding"
    ),
    "PATCH /v1/organizations/{org_id}/onboarding": OperationMeta(
        "PATCH", "/v1/organizations/{org_id}/onboarding"
    ),
    "GET /v1/organizations": OperationMeta("GET", "/v1/organizations"),
    "GET /v1/payments/resources": OperationMeta("GET", "/v1/payments/resources"),
    "POST /v1/payments/budget-topups": OperationMeta("POST", "/v1/payments/budget-topups"),
    "GET /v1/projects/{project_id}/policies": OperationMeta(
        "GET", "/v1/projects/{project_id}/policies"
    ),
    "POST /v1/projects/{project_id}/policies": OperationMeta(
        "POST", "/v1/projects/{project_id}/policies"
    ),
    "GET /v1/projects/{project_id}/policies/{policy_id}": OperationMeta(
        "GET", "/v1/projects/{project_id}/policies/{policy_id}"
    ),
    "PUT /v1/projects/{project_id}/policies/{policy_id}": OperationMeta(
        "PUT", "/v1/projects/{project_id}/policies/{policy_id}"
    ),
    "DELETE /v1/projects/{project_id}/policies/{policy_id}": OperationMeta(
        "DELETE", "/v1/projects/{project_id}/policies/{policy_id}"
    ),
    "POST /v1/projects/{project_id}/policy-evaluations": OperationMeta(
        "POST", "/v1/projects/{project_id}/policy-evaluations"
    ),
    "POST /v1/projects/{project_id}/policy-replays": OperationMeta(
        "POST", "/v1/projects/{project_id}/policy-replays"
    ),
    "GET /v1/projects": OperationMeta("GET", "/v1/projects"),
    "POST /v1/projects": OperationMeta("POST", "/v1/projects"),
    "GET /v1/projects/{project_id}": OperationMeta("GET", "/v1/projects/{project_id}"),
    "PATCH /v1/projects/{project_id}": OperationMeta("PATCH", "/v1/projects/{project_id}"),
    "DELETE /v1/projects/{project_id}": OperationMeta("DELETE", "/v1/projects/{project_id}"),
    "GET /v1/projects/{project_id}/metrics": OperationMeta(
        "GET", "/v1/projects/{project_id}/metrics"
    ),
    "GET /v1/regions": OperationMeta("GET", "/v1/regions"),
    "GET /v1/databases/{database_id}/replicas": OperationMeta(
        "GET", "/v1/databases/{database_id}/replicas"
    ),
    "POST /v1/databases/{database_id}/replicas": OperationMeta(
        "POST", "/v1/databases/{database_id}/replicas"
    ),
    "DELETE /v1/databases/{database_id}/replicas/{replica_id}": OperationMeta(
        "DELETE", "/v1/databases/{database_id}/replicas/{replica_id}"
    ),
    "GET /v1/projects/{project_id}/schema-annotations": OperationMeta(
        "GET", "/v1/projects/{project_id}/schema-annotations"
    ),
    "PUT /v1/projects/{project_id}/schema-annotations": OperationMeta(
        "PUT", "/v1/projects/{project_id}/schema-annotations"
    ),
    "DELETE /v1/projects/{project_id}/schema-annotations": OperationMeta(
        "DELETE", "/v1/projects/{project_id}/schema-annotations"
    ),
    "GET /v1/organizations/{org_id}/self-host-enrollments": OperationMeta(
        "GET", "/v1/organizations/{org_id}/self-host-enrollments"
    ),
    "POST /v1/organizations/{org_id}/self-host-enrollments": OperationMeta(
        "POST", "/v1/organizations/{org_id}/self-host-enrollments"
    ),
    "DELETE /v1/organizations/{org_id}/self-host-enrollments/{enrollment_id}": OperationMeta(
        "DELETE", "/v1/organizations/{org_id}/self-host-enrollments/{enrollment_id}"
    ),
    "POST /v1/organizations/{org_id}/self-host-enrollments/{enrollment_id}/rotate": OperationMeta(
        "POST", "/v1/organizations/{org_id}/self-host-enrollments/{enrollment_id}/rotate"
    ),
    "GET /v1/organizations/{org_id}/support/cases": OperationMeta(
        "GET", "/v1/organizations/{org_id}/support/cases"
    ),
    "POST /v1/organizations/{org_id}/support/cases": OperationMeta(
        "POST", "/v1/organizations/{org_id}/support/cases"
    ),
    "GET /v1/organizations/{org_id}/support/cases/{case_id}": OperationMeta(
        "GET", "/v1/organizations/{org_id}/support/cases/{case_id}"
    ),
    "PATCH /v1/organizations/{org_id}/support/cases/{case_id}": OperationMeta(
        "PATCH", "/v1/organizations/{org_id}/support/cases/{case_id}"
    ),
    "POST /v1/organizations/{org_id}/support/cases/{case_id}/messages": OperationMeta(
        "POST", "/v1/organizations/{org_id}/support/cases/{case_id}/messages"
    ),
    "POST /v1/internal/support/slack-event": OperationMeta(
        "POST", "/v1/internal/support/slack-event"
    ),
    "POST /v1/scan/text": OperationMeta("POST", "/v1/scan/text"),
    "GET /v1/organizations/{org_id}/usage": OperationMeta(
        "GET", "/v1/organizations/{org_id}/usage"
    ),
    "GET /v1/projects/{project_id}/usage": OperationMeta("GET", "/v1/projects/{project_id}/usage"),
    "GET /v1/projects/{project_id}/usage/agents": OperationMeta(
        "GET", "/v1/projects/{project_id}/usage/agents"
    ),
    "GET /v1/projects/{project_id}/webhooks": OperationMeta(
        "GET", "/v1/projects/{project_id}/webhooks"
    ),
    "POST /v1/projects/{project_id}/webhooks": OperationMeta(
        "POST", "/v1/projects/{project_id}/webhooks"
    ),
    "GET /v1/projects/{project_id}/webhooks/{webhook_id}": OperationMeta(
        "GET", "/v1/projects/{project_id}/webhooks/{webhook_id}"
    ),
    "PUT /v1/projects/{project_id}/webhooks/{webhook_id}": OperationMeta(
        "PUT", "/v1/projects/{project_id}/webhooks/{webhook_id}"
    ),
    "DELETE /v1/projects/{project_id}/webhooks/{webhook_id}": OperationMeta(
        "DELETE", "/v1/projects/{project_id}/webhooks/{webhook_id}"
    ),
    "POST /v1/projects/{project_id}/webhooks/{webhook_id}/test": OperationMeta(
        "POST", "/v1/projects/{project_id}/webhooks/{webhook_id}/test"
    ),
}
